toolbar:
  - styleselect | bold italic | table | uploadimage | undo redo
plugins:
  - image
  - link
  - table
  - uploadimage
# toolbar option must include "uploadimage" somewhere to have the button appear